# Site settings
name: Mayank Rajoria
title: Mayank Rajoria | Full Stack Software Engineer
description: Design-minded front-end software engineer focused on building beautiful interfaces and experiences
url: https://mayankrajoria.com/
baseurl: ""
email: brittany.chiang@gmail.com
cover: https://mayankrajoria.com/img/og.png
logo: https://mayankrajoria.com/img/emojis/technologist.png
resume: https://mayankrajoria.com/resume.pdf
social:
  - title: email
    url: mailto:brittany.chiang@gmail.com
  - title: github
    url: https://github.com/MayankR
  - title: twitter
    url: https://twitter.com/mayankrajoria
  - title: linkedin
    url: https://www.linkedin.com/in/mayank-rajoria

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
